---
- name: stop zookeeper
  service: 
    name: zookeeper
    state: stopped 
    enabled: no
  ignore_errors: true

- name: remove zookeeper user
  user:
    name: "{{ zookeeper_user }}"
    state: absent

- name: remove zookeeper group
  group:
    name: "{{ zookeeper_group }}"
    state: absent

- name: remove zookeeper directories
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/rc.d/init.d/zookeeper
    - /opt/zookeeper-{{ zookeeper_version }}
    - /etc/security/limits.d/99-zookeeper-nproc.conf
